version: "3.9"

services:

  app:
    image: node:17-alpine
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    entrypoint: npm
    command: run start:dev
    depends_on:
      - redis
      - mysql
      - postgresql
      - rabbitmq
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
      - TZ=America/Sao_Paulo
      - AMQP_HOST=rabbitmq
      - AMQP_PASSWORD=secret
      - AMQP_LOGIN=ff-svc-nestjs
      - RABBITMQ_CONNECTION_STRING=amqp://ff-svc-nestjs:secret@rabbitmq:5672
      - MYSQL_CONNECTION_STRING=mysql://ff-svc-nestjs:secret@mysql:3306/ff-svc-nestjs
      - POSTGRES_CONNECTION_STRING=postgresql://ff-svc-nestjs:secret@postgresql:5432/ff-svc-nestjs

  redis:
    image: bitnami/redis
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - TZ=America/Sao_Paulo
      - ALLOW_EMPTY_PASSWORD=yes

  rabbitmq:
    image: bitnami/rabbitmq
    volumes:
      - ff_rabbitmq:/bitnami
    expose:
      - 5672
      - 15672
      - 25672
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    environment:
      - TZ=America/Sao_Paulo
      - RABBITMQ_FORCE_BOOT=yes
      - RABBITMQ_PASSWORD=secret
      - RABBITMQ_ERL_COOKIE=secret
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_USERNAME=ff-svc-nestjs

  mysql:
    image: bitnami/mysql:5.7
    volumes:
      - ff_mysql:/bitnami/mysql/data
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_USER=ff-svc-nestjs
      - MYSQL_DATABASE=ff-svc-nestjs
      - MYSQL_PASSWORD=secret
      - ROW_FORMAT=COMPRESSED
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql:
    image: bitnami/postgresql
    volumes:
      - ff_postgresql:/bitnami/mysql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRESQL_USERNAME=ff-svc-nestjs
      - POSTGRESQL_DATABASE=ff-svc-nestjs
      - POSTGRESQL_PASSWORD=secret

# volumes

volumes:
  ff_rabbitmq: {}
  ff_mysql: {}
  ff_postgresql: {}
